const ActionTypes = {
    STORE_USER_INFO: 'STORE_USER_INFO',
    SET_BROWSER_WIDTH: 'SET_BROWSER_WIDTH',
    SET_MODAL_ACTIVE: 'SET_MODAL_ACTIVE',
    DISMISS_MODAL: 'DISMISS_MODAL',
    RESET_MODAL: 'RESET_MODAL'
};

export default ActionTypes;
