const CLIENT_CONSTANTS = {
    MOBILE_NAVBAR_BREAKPOINT: 992,

    BREAKPOINT_XS: 576,
    BREAKPOINT_SM: 768,
    BREAKPOINT_MD: 992,
    BREAKPOINT_LG: 1200,
    BREAKPOINT_XL: 9999999,

    PAGINATION_LIMIT: 7
};

export default CLIENT_CONSTANTS;
