---
#------------------------------------------------------------------------------
# Server Configurations
#
domain:
    url: ${DOMAIN_URL}

server:
    port: 8081
    error:
        whitelabel:
            enabled: false

#------------------------------------------------------------------------------
# AWS S3
#
cloud:
    aws:
        credentials:
            access-key: ${AWS_ACCESS_KEY}
            secret-key: ${AWS_ACCESS_SECRET}
        region:
            static: ${AWS_REGION}
        stack:
            auto: false

application:
    bucket:
        name: ${AWS_S3_BUCKET_NAME}

#------------------------------------------------------------------------------
# Google reCAPTCHA
#
recaptcha:
    validation:
        secret-key: ${CAPTCHA_SITE_SECRET}

#------------------------------------------------------------------------------
# MySQL Database config
#
spring:
    jpa:
        hibernate:
            ddl-auto: update
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:${DB_HOST}}:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver
    data:
        rest:
            base-path: '/api'
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2MB
            max-file-size: 50MB
            max-request-size: 50MB

    #------------------------------------------------------------------------------
    # OAuth2 Authorization Servers
    #
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_OAUTH2_CLIENT_ID}
                        client-secret: ${GOOGLE_OAUTH2_CLIENT_SECRET}

#------------------------------------------------------------------------------
# there is a bug in AWS S3 that's being suppressed here
#
logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error

        #------------------------------------------------------------------------------
        # MySQL trace queries
        #
        #org:
        #    hibernate:
        #        SQL: debug
        #        type:
        #        descriptor:
        #            sql: trace
